version: 2

sources:
  - name: wrk_training
    database: ic4_catalog  
    schema: wrk_training  
    tables:
      - name: churn_modelling
        columns:
          - name: customerid
            tests:
              - unique:
                  config:
                    severity: warn
              - not_null
      - name: world_population